<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="apoorv" failures="2" tests="2" name="Failure Test" time="0.05" errors="0" timestamp="2022-06-12T18:29:34 IST">
  <testcase classname="testCases.assertionsCheck" name="validateTitles" time="0.02">
    <failure type="java.lang.AssertionError" message="not found this thing expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: not found this thing expected [true] but found [false]
at testCases.assertionsCheck.validateTitles(assertionsCheck.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateTitles -->
  <testcase classname="testCases.SoftyAssert" name="validateTitles" time="0.006">
    <failure type="java.lang.AssertionError" message="cannot register user expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: cannot register user expected [true] but found [false]
at testCases.SoftyAssert.validateTitles(SoftyAssert.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- validateTitles -->
  <testcase classname="testCases.BaseTest" name="@BeforeSuite setup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite setup -->
  <testcase classname="testCases.BaseTest" name="@AfterSuite TearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite TearDown -->
</testsuite> <!-- Failure Test -->
